

- name: servicemesh | upgrade-pre | delete old sidecar injection
  shell: >
    {{ bin_dir }}/kubectl delete mutatingwebhookconfigurations istio-sidecar-injector-1-11-2
  ignore_errors: true

- name: servicemesh | delete old validating webhook
  shell: >
    {{ bin_dir }}/kubectl delete validatingwebhookconfigurations istio-validator-1-11-2-istio-system
  ignore_errors: true